# This is a development image for the front-end and back-end.
# It includes all development dependencies.
# This should be launched using docker-compose.
FROM node:16-slim
ENV NODE_ENV development

# Set the working directory to the root of the project.
WORKDIR /usr/src/medplum

# Expose ports
# 37001 for the front end server
# 37002 for the back end API server
EXPOSE 37001
EXPOSE 37002

# This will keep your container alive until it is told to stop.
# Using trap and wait will make your container react immediately to a stop request.
# Without trap/wait stopping will take a few seconds.
# See: https://stackoverflow.com/a/35770783
CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
