# This is the docker-compose file for the dev environment.
# It can be used to quickly run 4 services:
#   1) The front-end web server
#   2) The back-end API server
#   3) The Postgres database
#   4) The Redis cache
# You can start all services by running "docker-compose up"
version: '3.7'
services:
  dev:
    container_name: medplum_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - '37001:37001'
      - '37002:37002'
      - '37003:37003'
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    # Use a non-root user for all processes.
    # user: node
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  postgres:
    container_name: medplum_postgres
    image: postgres:12
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medplum
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
  postgres_test:
    container_name: medplum_postgres_test
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=medplum_test
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
  redis:
    container_name: medplum_redis
    image: redis:6
    command: redis-server --requirepass medplum
volumes:
  postgres-data:
